CREATE TABLE FUNKOS
(
    COD              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    NOMBRE           VARCHAR(255),
    MODELO           VARCHAR(255),
    PRECIO           real                 default 0,
    FECHALANZAMIENTO DATE,
    CREATEDAT        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);